version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_localstack_data: {}

networks:
  local: {}

services:
  vue:
    build:
      context: .
      dockerfile: ./compose/local/vue/Dockerfile
    container_name: local_vue
    platform: linux/x86_64
    volumes:
      - ./frontend:/app
    env_file:
      - ./.envs/.local/.vue
    ports:
      - "5173:5173"
    networks:
      - local
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - ./backend/:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    networks:
      - local
  postgres:
    image: postgres:14
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - local
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: local_mailhog
    ports:
      - "8025:8025"
    networks:
      - local
  redis:
    image: redis:6
    container_name: local_redis
    networks:
      - local
  celeryworker:
    <<: *django
    container_name: local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    entrypoint: /start-celeryworker
    networks:
      - local
  celerybeat:
    <<: *django
    container_name: local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    entrypoint: /start-celerybeat
    networks:
      - local
  flower:
    <<: *django
    container_name: local_flower
    ports:
      - "5555:5555"
    entrypoint: /start-flower
    networks:
      - local
  localstack:
    build:
      context: .
      dockerfile: ./compose/local/localstack/Dockerfile
    container_name: local_localstack
    hostname: localstack.localhost
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local