version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  vue:
    build:
      context: .
      dockerfile: ./compose/local/vue/Dockerfile
    container_name: local_vue
    platform: linux/x86_64
    volumes:
      - ./frontend/:/app:z
    env_file:
      - ./.envs/.local/.vue
    ports:
      - "5173:5173"
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - ./backend/:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: local_redis

  celeryworker:
    <<: *django
    container_name: local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    entrypoint: /start-celeryworker

  celerybeat:
    <<: *django
    container_name: local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    entrypoint: /start-celerybeat

  flower:
    <<: *django
    container_name: local_flower
    ports:
      - "5555:5555"
    entrypoint: /start-flower

  localstack:
    image: localstack/localstack:1.0.3
    container_name: local_localstack
    ports:
      - "4566:4566"