# Generated by Django 3.2.14 on 2022-12-20 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'user_type',
                    models.CharField(
                        choices=[('O', 'Owner'), ('S', 'Student'), ('T', 'Teacher'), ('A', 'Administrator')],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                (
                    'address',
                    models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)]),
                ),
                (
                    'phone_number',
                    models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(6)]),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('C', 'College'), ('H', 'High School'), ('E', 'Elementary School')], max_length=1
                    ),
                ),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.country')),
                ('members', models.ManyToManyField(through='organizations.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='name2address_unique'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='organization2user_unique'),
        ),
    ]
